- name: Atualizar pacotes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar MySQL 8
  apt:
    name: mysql-server
    state: present

- name: Habilitar e iniciar serviço MySQL
  systemd:
    name: mysql
    enabled: yes
    state: started

- name: Verificar método de autenticação do usuário root
  command: "mysql -NBe \"SELECT plugin FROM mysql.user WHERE user='root' AND host='localhost';\""
  register: mysql_auth_plugin
  changed_when: false
  ignore_errors: true

- name: Alterar autenticação do root para senha, se necessário
  command: >
    mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  become: true
  when: "'auth_socket' in mysql_auth_plugin.stdout"

- name: Criar banco de dados do Zabbix
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: true
