---
- name: Verificar se o sistema é Ubuntu 24.04
  ansible.builtin.fail:
    msg: "Este playbook só pode ser executado no Ubuntu 24.04!"
  when: ansible_distribution != "Ubuntu" or ansible_distribution_version != "24.04"

- name: Atualizar cache do APT
  apt:
    update_cache: yes

- name: Instalar dependências para MySQL e Python
  apt:
    name:
      - python3-pymysql
      - python3-mysqldb
      - mysql-client
      - python3-mysql.connector
    state: present
