---
- name: Atualizar cache do APT
  apt:
    update_cache: yes

- name: Instalar dependências para MySQL e Python
  apt:
    name:
      - python3-pymysql
      - python3-mysqldb
      - mysql-client
      - python3-mysql.connector
    state: present
