---
---
- name: Instalar pacotes Zabbix Agent e SNMP
  apt:
    name:
      - zabbix-agent
      - snmp
      - snmp-mibs-downloader
      - snmpd  # Opcional: só inclua se quiser configurar SNMP local
    state: latest
    update_cache: yes
  become: true
  notify: Restart Zabbix Agent

- name: Configurar Zabbix Agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0640
  become: true
  notify: Restart Zabbix Agent

- name: Habilitar e iniciar serviços
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - zabbix-agent
    - snmpd  # Opcional
  become: true
# tasks file for zabbix-agent-snmp
